name: Run NumberWorder.py in Github Actions

on:
  push:
    branches: 
      - master
  schedule: 
  - cron: '0 9 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Run file
      run: python NumberWorder.py
